apiVersion: v1
kind: ConfigMap
metadata:
  name: post-install-configmap
  annotations:
    helm.sh/hook: "post-install, post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook-weight: "0"
data:
  config.conf: |
    KEY_CONFIG_POST_INSTALL: key_config_post_install
  run.sh: |
    #!/bin/sh
    set -x
    ls /mnt/configmap/
    cat /mnt/configmap/config.conf
    ls /mnt/secret
    cat /mnt/secret/secret.conf
