apiVersion: v1
kind: Secret
metadata:
  name: post-install-secret
  annotations:
    helm.sh/hook: "post-install, post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook-weight: "0"
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  secret.conf: |
    KEY_SECRET_POST_INSTALL: key_secret_post_install
