apiVersion: v1
kind: Secret
metadata:
  name: pre-install-secret
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook-weight: "0"
    helm.sh/resource-policy: keep
type: Opaque
data:
  KEY_SECRET_PRE_INSTALL: a2V5X3NlY3JldF9wcmVfaW5zdGFsbA==
