apiVersion: v1
kind: ConfigMap
metadata:
  name: pre-install-configmap
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook-weight: "0"
data:
  KEY_CONFIG_PRE_INSTALL: key_config_pre_install
